---
# tasks file for node_exporter_role
- name: Add the group
  become: yes
  ansible.builtin.group:
    name: '{{ group }}'

- name: Add the user
  become: yes
  ansible.builtin.user:
    name: '{{ user }}'

- name: get & extract package
  become: yes
  ansible.builtin.unarchive:
    owner: '{{ user }}'
    group: '{{ group }}'
    src: files/{{ pkg_node_exporter }}
    dest: /tmp
    validate_certs: no
    list_files: yes
  register: archive_contents

- debug: 'msg="Subfolder: {{ archive_contents.files }}"'

- name: copy to path
  become: yes
  ansible.builtin.copy:
    owner: '{{ user }}'
    group: '{{ group }}'
    src: '/tmp/{{ archive_contents.files[0] | lower }}node_exporter'
    dest: '{{ path }}'
    remote_src: yes
    mode: 0755
  register: copy_result

- debug: 'msg="Results: {{ copy_result }}"'

- name: env file
  become: yes 
  ansible.builtin.template:
    src: templates/node_exporter.j2
    dest: /etc/default/node_exporter
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: 0644

- name: copy template of service file
  become: yes
  ansible.builtin.template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart node_exporter
  register: template_result

- debug: 'msg="Results: {{ template_result }}"'

- name: make prometheus conf dir
  become: yes
  ansible.builtin.file:
    owner: '{{ user }}'
    group: '{{ group }}'
    state: 'directory'
    path: '{{ conf_dir }}'
    mode: 644

- name: run openssl to get certs & keys for node_exporter
  become: yes
  ansible.builtin.shell: |
    cd {{ conf_dir }}
    /usr/bin/openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout \
    {{ ne_key }} -out {{ ne_crt }} \
    -subj "/C=BE/ST=Antwerp/L=Brasschaat/O=Inuits/CN={{ host_name }}" -addext \
    "subjectAltName = DNS:{{ host_name }}"


- name: Set diff. modes for certs & keys
  become: yes
  ansible.builtin.shell: |
    cd {{ conf_dir }} && chmod -R 0600 *.crt && chmod -R 0644 *.key

- name: Set owners for nod_exporter keys
  become: yes
  ansible.builtin.file:
    path: '{{ conf_dir }}'
    owner: '{{ user }}'
    group: '{{ group }}'
    recurse: yes

  tags: test2

- name: make web.yml for tls connections
  become: yes
  ansible.builtin.copy:
    owner: '{{ user }}'
    group: '{{ group }}'
    dest: '{{ conf_dir }}/web.yml'
    content: |
      tls_server_config:
        cert_file: {{ conf_dir }}/{{ ne_crt }}
        key_file: {{ conf_dir }}/{{ ne_key }}
    mode: 0644
  notify:
  - restart node_exporter

    
    