---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu_xenial_1604
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      host_vars: /root/netol_do/diplom/ansible/playbook/inventory/
      group_vars: /root/netol_do/diplom/ansible/playbook/group_vars/

verifier:
  name: ansible
